services:
  frontend:
    container_name: angular
    build: ./angular
    image: jwt-angular
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart:
      unless-stopped
    networks:
      - app-network

  backend:
    container_name: springboot
    build: ./springboot
    image: jwt-springboot
    environment:
      POSTGRES_DB: jwt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - database
    restart:
      unless-stopped
    networks:
      - app-network

  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_DB: jwt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5445:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
