services:
  backend:
    container_name: springboot
    build: ./springboot
    environment:
      POSTGRES_DB: jwt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    container_name: angular
    build: ./angular
    ports:
      - "4200:80"
    networks:
      - app-network
    depends_on:
      - database
    restart:
      on-failure

  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_DB: jwt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5445:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
