name: jwt
services:
  database:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_DB=jwt
      - POSTGRES_USER=jwt
      - POSTGRES_PASSWORD=jwt
    ports:
      - 5445:5432